# Collector specific configuration
# sample_url: "https://www.nhc.noaa.gov/productexamples/NHC_JSON_Sample.json"
base_url: "https://www.nhc.noaa.gov/CurrentStorms.json"
account: "account"
container: "container"
key: "key"
ghaction_url: "ghactionurl"
ghp: "ghp"